package com.weatherviewer.model;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;
import lombok.experimental.Accessors;

import java.time.LocalDateTime;
import java.util.UUID;

/**
 * Common base for all JPA entities.
 * <p>
 * Provides a UUID primary key generated by the database and a
 * {@code createdAt} timestamp that is stamped automatically on first
 * persist via {@link #onCreate()}. Entities extend this class instead of
 * redeclaring identifier/audit fields individually.
 */
@Getter
@Setter
@MappedSuperclass
@Accessors(chain = true)
public class BaseEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private UUID id;

    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /**
     * JPA lifecycle callback that stamps {@link #createdAt} with the
     * current time right before the entity is first persisted.
     */
    @PrePersist
    protected void onCreate() {
        this.createdAt = LocalDateTime.now();
    }

}
