spring.application.name=WeatherViewer
spring.config.import=optional:file:./.env

springdoc.swagger-ui.path=/swagger-ui.html

weather.base.api.url=https://api.openweathermap.org
weather.api.url.suffix=/data/2.5/weather
weather.api.key=${WEATHER_API_KEY}